blank_issues_enabled: false
contact_links:
  - name: Chargebee Support
    url: https://support.chargebee.com/
    about: If you are having any queries regarding the implementation? Reach out to https://support.chargebee.com/.